# Generated by Django 2.2.28 on 2022-08-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_tyidhhd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tyidhhd",
            name="namert",
        ),
        migrations.AddField(
            model_name="tyidhhd",
            name="namert233",
            field=models.TextField(blank=True),
        ),
    ]
