# Generated by Django 2.2.28 on 2022-08-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220801_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vretyu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vgeyes', models.TextField()),
            ],
        ),
    ]
