# Generated by Django 2.2.28 on 2022-08-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vretyu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vretyu',
        ),
    ]
